apiVersion: v1
kind: Pod
metadata:
  name: pvc-loader
  namespace: kubeflow
spec:
  volumes:
    - name: azurefile
      persistentVolumeClaim:
        claimName: azurefile
  containers:
    - name: pvc-loader
      image: ubuntu
      volumeMounts:
      - name: azurefile
        mountPath: /data
      command: ["/bin/bash", "-ecx", "while :; do printf '.'; sleep 5 ; done"]
